def get_roles():
    return [
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "SWE Intern - Commercial & Investment Bank",
            "JPMorganChase", "Roles - Internship",
            "Athena application developer working on server workloads migration from on-premise to public cloud, and platform & tooling workstreams within Currencies & Emerging Markets (CEM).",
            "Worked on cloud migration and platform tooling for the CEM line-of-business under the Commercial & Investment Bank.",
            "Apr 2025 – Present", "Apr 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Youth Corps Aspirant",
            "Youth Corps Singapore", "Roles - Community",
            "Participated in the Youth Corps Leaders Programme, contributing to community engagement projects and leadership training focused on social impact.",
            "Worked with diverse teams to support ground-up initiatives addressing community needs while developing teamwork, communication and responsible leadership skills.",
            "Oct 2025 – Present", "Oct 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Head of Operations & Finance",
            "ASEAN Youth Advocates Network", "Roles - Leadership",
            "Led operational and financial functions to strengthen organisational sustainability and programme delivery across regional teams.",
            "Redesigned internal workflows, budgeting, and reporting structures. Supported delivery of student-facing programmes aimed at improving youth awareness of regional issues and civic engagement.",
            "Jul 2025 – Present", "Jul 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Volunteer - Cyber Youth Collective, Programmes Team",
            "YouthTechSG", "Roles - Community",
            "Part of Singapore's largest youth-in-tech movement, empowering youths and championing digital resilience, opportunity and representation.",
            "Collaborating with partners across government, industry, and education to support youth in tech.",
            "Jun 2025 – Present", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Networks Engagement Manager - Networks Division",
            "Advisory Singapore", "Roles - Leadership",
            "Building partnerships with industry leaders and stakeholders to drive impactful career support initiatives for youth in Singapore.",
            "Engaged in technical restructuring of the Networks department database. Organised events, mentorship programs and collaborative projects bridging students with industry experts.",
            "Aug 2024 – Present", "Aug 2024",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Executive Committee Member",
            "NYP AWS Cloud Club", "Roles - Leadership",
            "Organised workshops and hands-on projects to deepen members' understanding of AWS and cloud computing.",
            "Facilitated knowledge-sharing sessions and supported collaborative initiatives applying cloud technologies to real-world problems.",
            "Apr 2024 – Present", "Apr 2024",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Head of Liaison",
            "NYP LEO Club", "Roles - Leadership",
            "Led liaison efforts for the LEO Club at Nanyang Polytechnic.",
            "",
            "Apr 2024 – Mar 2025", "Apr 2024",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Assistant Sports Secretary - Social Sports Dept",
            "NYP School of IT", "Roles - Leadership",
            "Supported planning and execution of sports and social activities for School of Information Technology students.",
            "Assisted with coordination, logistics and administrative matters including scheduling and internal communications.",
            "Oct 2023 – Mar 2025", "Oct 2023",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Sub-Committee Member (InfoSec)",
            "NYP InfoSec", "Roles - Club",
            "Active sub-committee member of the NYP Information Security club.",
            "",
            "Mar 2024 – Feb 2025", "Mar 2024",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Roles & Activities", "Roles & Activities",
            "Sub-Committee Member (AI)",
            "NYP AI Club", "Roles - Club",
            "Active sub-committee member of the NYP Artificial Intelligence club.",
            "",
            "Feb 2024 – Jan 2025", "Feb 2024",
            "", "", "", "", "", "",
        ),
    ]
