def get_certs3():
    return [
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations",
            "LinkedIn Learning", "Certifications - PM",
            "Core project management principles and best practices.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Ethics",
            "LinkedIn Learning", "Certifications - PM",
            "Ethics and professional responsibility in project management.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Requirements",
            "LinkedIn Learning", "Certifications - PM",
            "Gathering and managing project requirements.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Schedules",
            "LinkedIn Learning", "Certifications - PM",
            "Scheduling techniques for effective project delivery.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Budgets",
            "LinkedIn Learning", "Certifications - PM",
            "Budget planning and cost management for projects.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Teams",
            "LinkedIn Learning", "Certifications - PM",
            "Building and leading high-performing project teams.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Communication",
            "LinkedIn Learning", "Certifications - PM",
            "Effective communication strategies for project managers.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Project Management Foundations: Risk",
            "LinkedIn Learning", "Certifications - PM",
            "Risk identification, analysis, and mitigation.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Managing Project Stakeholders",
            "LinkedIn Learning", "Certifications - PM",
            "Stakeholder engagement and management strategies.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Business Analyst and Project Manager Collaboration",
            "LinkedIn Learning", "Certifications - PM",
            "Effective collaboration between BA and PM roles.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "What Is Business Analysis?",
            "LinkedIn Learning", "Certifications - BA",
            "Introduction to business analysis fundamentals.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Business Analysis Foundations",
            "LinkedIn Learning", "Certifications - BA",
            "Core business analysis concepts and techniques.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Agile Requirements Foundations",
            "LinkedIn Learning", "Certifications - BA",
            "Requirements management in agile environments.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Business Benefits Realisation Foundations",
            "LinkedIn Learning", "Certifications - BA",
            "Tracking and delivering business benefits.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Business Analysis Foundations: Business Process Modelling",
            "LinkedIn Learning", "Certifications - BA",
            "Modelling and optimizing business processes.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Requirements Elicitation: Stakeholder Conversations",
            "LinkedIn Learning", "Certifications - BA",
            "Techniques for eliciting requirements from stakeholders.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
    ]
