def get_certs():
    # Same tuple format as projects: (section, category, subsection, title,
    #   byline, tag, summary, description, date_label, date_value,
    #   deliverables, challenges, future_improvements, extra_notes,
    #   image_path, external_link)
    return [
        (
            "experience", "Certifications", "Certifications",
            "AWS Certified Cloud Practitioner",
            "Amazon Web Services", "Certifications - AWS",
            "Foundational cloud credential validating core AWS concepts.",
            "Completed and applied fundamentals in cloud architecture and serverless tooling.",
            "Certified", "Jul 2024",
            "", "", "", "",
            "../static/images/Certifications/AWS/AWSTrainingAndCertification/ACP/AWSCertifiedCloudPractitioner_Certificate.jpg",
            "https://www.credly.com/badges/199c0edc-3abc-448f-9bf3-2b41a629398c/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "TensorFlow Developer Certificate",
            "TensorFlow Certificate Program", "Certifications - ML",
            "Professional certification in TensorFlow for machine learning.",
            "", "Certified", "May 2024",
            "", "", "", "", "",
            "https://www.credential.net/387b9a62-db88-4df1-92f2-e29925760fb3",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Professional Scrum Product Owner I (PSPO I)",
            "Scrum.org", "Certifications - Agile",
            "Professional Scrum Product Owner certification.",
            "", "Certified", "Jul 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/6b1120c3-36f0-46bc-96e6-1ac032b0f608/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "PCEP - Certified Entry-Level Python Programmer",
            "OpenEDG Python Institute", "Certifications - Python",
            "Entry-level Python programming certification.",
            "", "Certified", "Jul 2024",
            "", "", "", "", "",
            "https://verify.openedg.org/?id=myQY.Trpt.cLkx",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Google Data Analytics Specialization",
            "Google / Coursera", "Certifications - Google",
            "Professional certificate in data analytics (8 courses).",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.coursera.org/account/accomplishments/specialization/ZXKJHEUCE27X",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AI4I - Literacy in AI",
            "AI Singapore", "Certifications - AI",
            "Foundational AI literacy programme by AI Singapore.",
            "", "Completed", "Nov 2023",
            "", "", "", "", "",
            "https://learn.aisingapore.org/certificate-verification/815F4B0CB3-7EF3E14120-138D6BF39/",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AI4I - Foundations in AI",
            "AI Singapore", "Certifications - AI",
            "Intermediate AI foundations programme by AI Singapore.",
            "", "Completed", "Feb 2024",
            "", "", "", "", "",
            "https://learn.aisingapore.org/certificate-verification/815F78D498-7337A03566-138D6BF39/",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AI4I - AI Project Lifecycle",
            "AI Singapore", "Certifications - AI",
            "AI project lifecycle management programme by AI Singapore.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://learn.aisingapore.org/certificate-verification/8383D51459-8383D512CE-138D6BF39/",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Introduction to Generative AI",
            "Google Cloud", "Certifications - Google",
            "Foundational understanding of generative AI concepts.",
            "", "Completed", "Sep 2023",
            "", "", "", "", "",
            "https://www.cloudskillsboost.google/public_profiles/2dd8854f-cd4e-49ac-8c16-ac8c5a6ef830/badges/4978373",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Knowledge: Cloud Essentials",
            "Amazon Web Services", "Certifications - AWS",
            "AWS Cloud Essentials knowledge path.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/d8fb5d9d-e204-402f-b380-e0d2d5e4be58/linked_in_profile",
        ),
    ]
