def get_certs2():
    return [
        (
            "experience", "Certifications", "Certifications",
            "AWS Cloud Quest: Cloud Practitioner",
            "Amazon Web Services", "Certifications - AWS",
            "Hands-on cloud practitioner quest.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/33f8ad44-5e7e-4c14-8352-f16f02f66ad8/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Educate Machine Learning - DeepRacer",
            "Amazon Web Services", "Certifications - AWS",
            "ML fundamentals through AWS DeepRacer.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/941a2d43-6036-4a2a-a734-060cc5c7f8d8/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Educate ML Foundations",
            "Amazon Web Services", "Certifications - AWS",
            "Machine learning foundations on AWS.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/f252b201-e2b7-4408-88e0-86e54b21ef42/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Educate Getting Started with Cloud Ops",
            "Amazon Web Services", "Certifications - AWS",
            "Cloud operations fundamentals.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/30b1b06e-e635-43b9-ba59-963b662f35ac/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Educate Getting Started with Storage",
            "Amazon Web Services", "Certifications - AWS",
            "Cloud storage fundamentals.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/622a5cbf-db24-48ee-85d2-994472ccea2f/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Educate Introduction to Cloud 101",
            "Amazon Web Services", "Certifications - AWS",
            "Introduction to cloud computing.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/32962e61-83a9-406b-9e7c-48ad374f0d0a/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Cloud Clubs Amplify Web Dev Camper",
            "AWS Community", "Certifications - AWS",
            "Web development with AWS Amplify.",
            "", "Completed", "May 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/5cfe87cc-4cdb-43d4-9549-acd84897a553/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Cloud Clubs ML Camper",
            "AWS Community", "Certifications - AWS",
            "Machine learning camp by AWS Cloud Clubs.",
            "", "Completed", "May 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/e2fd3bfd-2f6c-4009-bc40-190f7d729610/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "C# for .NET Developers",
            "Board Infinity / Coursera", "Certifications - Dev",
            "C# programming for .NET development.",
            "", "Completed", "May 2024",
            "", "", "", "", "",
            "https://www.coursera.org/account/accomplishments/records/CUEXGBYHBXG7",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Exploring Cybersecurity Seminar",
            "Acumen IT", "Certifications - Security",
            "Career paths and practical insights in cybersecurity.",
            "", "Completed", "Apr 2024",
            "", "", "", "", "",
            "https://www.credly.com/badges/ea5d0c79-7194-41d5-b051-77ac3ffa5883/linked_in_profile",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Singapore Computer Society - Student Chapter",
            "Singapore Computer Society", "Certifications - Membership",
            "SCS student membership.",
            "", "Member Since", "Sep 2024",
            "", "", "", "", "",
            "https://scs.org.sg/membership/verify?id=ae5e8ecb-8f32-46d8-9d0f-21a88411878d",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Introducing Generative AI with AWS",
            "Udacity", "Certifications - AI",
            "Generative AI fundamentals with AWS services.",
            "", "Completed", "May 2025",
            "", "", "", "", "",
            "www.udacity.com/certificate/e/67dba36a-4e69-11f0-acf1-8b5346f29642",
        ),
    ]
