def get_certs4():
    return [
        (
            "experience", "Certifications", "Certifications",
            "Machine Learning Foundations: Statistics",
            "LinkedIn Learning", "Certifications - Data",
            "Statistical foundations for machine learning.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Big Data Analytics with Hadoop and Apache Spark",
            "LinkedIn Learning", "Certifications - Data",
            "Big data processing with Hadoop and Spark.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Learning Data Science: Understanding the Basics",
            "LinkedIn Learning", "Certifications - Data",
            "Introduction to data science concepts.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Learning Data Analytics: 1 Foundations",
            "LinkedIn Learning", "Certifications - Data",
            "Core data analytics foundations.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Learning Data Analytics Part 2: Extending and Applying Core Knowledge",
            "LinkedIn Learning", "Certifications - Data",
            "Advanced data analytics techniques.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Introduction to Career Skills in Data Analytics",
            "LinkedIn Learning", "Certifications - Data",
            "Career-focused data analytics skills.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Learning Docker",
            "LinkedIn Learning", "Certifications - DevOps",
            "Docker fundamentals for containerized applications.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Docker: Your First Project",
            "LinkedIn Learning", "Certifications - DevOps",
            "Hands-on Docker project from scratch.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Learning Docker Compose",
            "LinkedIn Learning", "Certifications - DevOps",
            "Multi-container orchestration with Docker Compose.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Learning Linux Command Line",
            "LinkedIn Learning", "Certifications - DevOps",
            "Essential Linux CLI skills.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Red Hat Certified Engineer (EX294) Cert Prep: Foundations of Ansible",
            "LinkedIn Learning", "Certifications - DevOps",
            "Ansible automation foundations for RHCE prep.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Complete Guide to Red Hat Enterprise Linux 9",
            "LinkedIn Learning", "Certifications - DevOps",
            "Comprehensive RHEL 9 administration guide.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "CompTIA A+ Core 1 (220-1101) Cert Prep",
            "LinkedIn Learning", "Certifications - IT",
            "CompTIA A+ Core 1 exam preparation.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "CompTIA A+ Core 2 (220-1102) Cert Prep",
            "LinkedIn Learning", "Certifications - IT",
            "CompTIA A+ Core 2 exam preparation.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Programming Foundations: Fundamentals",
            "LinkedIn Learning", "Certifications - Dev",
            "Core programming concepts and practices.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Programming Foundations: Beyond the Fundamentals",
            "LinkedIn Learning", "Certifications - Dev",
            "Advanced programming concepts.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Collaborating with Microsoft 365",
            "LinkedIn Learning", "Certifications - Productivity",
            "Team collaboration with Microsoft 365 tools.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Managing Projects with Microsoft 365",
            "LinkedIn Learning", "Certifications - Productivity",
            "Project management using Microsoft 365.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Optimising Your Work with Microsoft 365",
            "LinkedIn Learning", "Certifications - Productivity",
            "Productivity optimization with Microsoft 365.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Managing Data with Microsoft 365",
            "LinkedIn Learning", "Certifications - Productivity",
            "Data management within Microsoft 365 ecosystem.",
            "", "Completed", "Jun 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Google Cloud Professional ML Engineer Cert Prep",
            "LinkedIn Learning", "Certifications - Cloud",
            "Google Cloud ML Engineer exam preparation.",
            "", "Completed", "Aug 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Prompt Engineering: How to Talk to the AIs",
            "LinkedIn Learning", "Certifications - AI",
            "Effective prompt engineering techniques.",
            "", "Completed", "Aug 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "What Is Generative AI?",
            "LinkedIn Learning", "Certifications - AI",
            "Overview of generative AI concepts and applications.",
            "", "Completed", "Aug 2025",
            "", "", "", "", "", "",
        ),
        (
            "experience", "Certifications", "Certifications",
            "AWS Certified Solutions Architect - Associate",
            "Amazon Web Services", "Certifications - AWS",
            "AWS Solutions Architect Associate certification.",
            "", "Completed", "Mar 2026",
            "", "", "", "", "",
            "https://www.credly.com/badges/9a168a86-e054-40a5-966d-3abf14dff887",
        ),
        (
            "experience", "Certifications", "Certifications",
            "SCS-AWS GenAI (Foundational) Programme",
            "Singapore Computer Society", "Certifications - AI",
            "Generative AI foundations programme by SCS and AWS.",
            "", "Completed", "Mar 2026",
            "", "", "", "", "",
            "https://scs.org.sg/membership/verify?id=db459386-0bd8-4fa8-8f51-3fc818cafe9c",
        ),
        (
            "experience", "Certifications", "Certifications",
            "SCS-Huawei ICT Academy Essential Skills Programme",
            "Singapore Computer Society", "Certifications - ICT",
            "ICT essential skills programme by SCS and Huawei.",
            "", "Completed", "Dec 2025",
            "", "", "", "", "",
            "https://scs.org.sg/membership/verify?id=29f5cc14-fd1d-4e46-a40e-1eeb012e4327",
        ),
        (
            "experience", "Certifications", "Certifications",
            "Zooniverse Citizen Science Certificate",
            "Zooniverse", "Certifications - Science",
            "Citizen science research contributions via Zooniverse.",
            "", "Completed", "Jul 2025",
            "", "", "", "", "", "",
        ),
    ]
